// GENERATED by scripts/generate-db-types.ts from supabase/migrations — do not edit.
// Regenerate with `npm run db:types` after changing a migration.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  __InternalSupabase: { PostgrestVersion: "13" };
  public: {
    Tables: {
      amenities: {
        Row: {
          id: string;
          name: string;
          icon: string | null;
          active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          icon?: string | null;
          active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          icon?: string | null;
          active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
        ];
      };
      app_settings: {
        Row: {
          id: boolean;
          church_name: string;
          app_name: string;
          timezone: string;
          contact_email: string | null;
          contact_phone: string | null;
          booking_interval_minutes: number;
          default_max_advance_value: number;
          default_max_advance_unit: Database["public"]["Enums"]["advance_unit"];
          min_lead_time_minutes: number;
          bookable_day_start: string;
          bookable_day_end: string;
          allow_guest_cancellation: boolean;
          extra_admin_notification_emails: string[];
          email_sender_name: string;
          updated_at: string;
          updated_by: string | null;
        };
        Insert: {
          id?: boolean;
          church_name?: string;
          app_name?: string;
          timezone?: string;
          contact_email?: string | null;
          contact_phone?: string | null;
          booking_interval_minutes?: number;
          default_max_advance_value?: number;
          default_max_advance_unit?: Database["public"]["Enums"]["advance_unit"];
          min_lead_time_minutes?: number;
          bookable_day_start?: string;
          bookable_day_end?: string;
          allow_guest_cancellation?: boolean;
          extra_admin_notification_emails?: string[];
          email_sender_name?: string;
          updated_at?: string;
          updated_by?: string | null;
        };
        Update: {
          id?: boolean;
          church_name?: string;
          app_name?: string;
          timezone?: string;
          contact_email?: string | null;
          contact_phone?: string | null;
          booking_interval_minutes?: number;
          default_max_advance_value?: number;
          default_max_advance_unit?: Database["public"]["Enums"]["advance_unit"];
          min_lead_time_minutes?: number;
          bookable_day_start?: string;
          bookable_day_end?: string;
          allow_guest_cancellation?: boolean;
          extra_admin_notification_emails?: string[];
          email_sender_name?: string;
          updated_at?: string;
          updated_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "app_settings_updated_by_fkey";
            columns: ["updated_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      audit_logs: {
        Row: {
          id: number;
          actor_user_id: string | null;
          actor_kind: Database["public"]["Enums"]["actor_kind"];
          action: string;
          entity_type: string;
          entity_id: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: never;
          actor_user_id?: string | null;
          actor_kind: Database["public"]["Enums"]["actor_kind"];
          action: string;
          entity_type: string;
          entity_id?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: never;
          actor_user_id?: string | null;
          actor_kind?: Database["public"]["Enums"]["actor_kind"];
          action?: string;
          entity_type?: string;
          entity_id?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "audit_logs_actor_user_id_fkey";
            columns: ["actor_user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      email_logs: {
        Row: {
          id: string;
          reservation_id: string | null;
          recipient: string;
          event_type: string;
          status: Database["public"]["Enums"]["email_status"];
          provider_message_id: string | null;
          error_message: string | null;
          attempt_count: number;
          last_attempt_at: string | null;
          sent_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          reservation_id?: string | null;
          recipient: string;
          event_type: string;
          status?: Database["public"]["Enums"]["email_status"];
          provider_message_id?: string | null;
          error_message?: string | null;
          attempt_count?: number;
          last_attempt_at?: string | null;
          sent_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          reservation_id?: string | null;
          recipient?: string;
          event_type?: string;
          status?: Database["public"]["Enums"]["email_status"];
          provider_message_id?: string | null;
          error_message?: string | null;
          attempt_count?: number;
          last_attempt_at?: string | null;
          sent_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "email_logs_reservation_id_fkey";
            columns: ["reservation_id"];
            isOneToOne: false;
            referencedRelation: "reservations";
            referencedColumns: ["id"];
          },
        ];
      };
      ministries: {
        Row: {
          id: string;
          name: string;
          active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
        ];
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: string;
          title: string;
          message: string;
          reservation_id: string | null;
          read_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: string;
          title: string;
          message: string;
          reservation_id?: string | null;
          read_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: string;
          title?: string;
          message?: string;
          reservation_id?: string | null;
          read_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "notifications_reservation_id_fkey";
            columns: ["reservation_id"];
            isOneToOne: false;
            referencedRelation: "reservations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "notifications_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string;
          role: Database["public"]["Enums"]["app_role"];
          active: boolean;
          email_notifications: boolean;
          invited_by: string | null;
          created_at: string;
          updated_at: string;
          invitation_accepted_at: string | null;
          first_login_at: string | null;
        };
        Insert: {
          id: string;
          email: string;
          full_name: string;
          role?: Database["public"]["Enums"]["app_role"];
          active?: boolean;
          email_notifications?: boolean;
          invited_by?: string | null;
          created_at?: string;
          updated_at?: string;
          invitation_accepted_at?: string | null;
          first_login_at?: string | null;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string;
          role?: Database["public"]["Enums"]["app_role"];
          active?: boolean;
          email_notifications?: boolean;
          invited_by?: string | null;
          created_at?: string;
          updated_at?: string;
          invitation_accepted_at?: string | null;
          first_login_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "profiles_invited_by_fkey";
            columns: ["invited_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      rate_limit_events: {
        Row: {
          id: number;
          bucket: string;
          key_hash: string;
          created_at: string;
        };
        Insert: {
          id?: never;
          bucket: string;
          key_hash: string;
          created_at?: string;
        };
        Update: {
          id?: never;
          bucket?: string;
          key_hash?: string;
          created_at?: string;
        };
        Relationships: [
        ];
      };
      reservation_series: {
        Row: {
          id: string;
          status: string;
          room_id: string;
          created_by_user_id: string;
          frequency: string;
          interval_count: number;
          weekdays: number[];
          weekday: number | null;
          month_ordinals: number[];
          month_ordinal: number | null;
          day_of_month: number | null;
          month_of_year: number | null;
          instance_limit: number;
          start_date: string;
          end_date: string | null;
          local_start_time: string;
          local_end_time: string;
          timezone: string;
          requester_first_name: string;
          requester_last_name: string;
          requester_email: string;
          requester_phone: string;
          ministry_id: string | null;
          other_ministry_name: string | null;
          purpose: string;
          estimated_attendance: number;
          setup_requirements: string | null;
          requester_notes: string | null;
          admin_notes: string | null;
          notify_requester: boolean;
          materialized_through: string | null;
          paused_reason: string | null;
          materialization_claim_id: string | null;
          materialization_claimed_at: string | null;
          ended_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          status?: string;
          room_id: string;
          created_by_user_id: string;
          frequency: string;
          interval_count?: number;
          weekdays?: number[];
          weekday?: number | null;
          month_ordinals?: number[];
          month_ordinal?: number | null;
          day_of_month?: number | null;
          month_of_year?: number | null;
          instance_limit?: number;
          start_date: string;
          end_date?: string | null;
          local_start_time: string;
          local_end_time: string;
          timezone: string;
          requester_first_name: string;
          requester_last_name: string;
          requester_email: string;
          requester_phone: string;
          ministry_id?: string | null;
          other_ministry_name?: string | null;
          purpose: string;
          estimated_attendance: number;
          setup_requirements?: string | null;
          requester_notes?: string | null;
          admin_notes?: string | null;
          notify_requester?: boolean;
          materialized_through?: string | null;
          paused_reason?: string | null;
          materialization_claim_id?: string | null;
          materialization_claimed_at?: string | null;
          ended_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          status?: string;
          room_id?: string;
          created_by_user_id?: string;
          frequency?: string;
          interval_count?: number;
          weekdays?: number[];
          weekday?: number | null;
          month_ordinals?: number[];
          month_ordinal?: number | null;
          day_of_month?: number | null;
          month_of_year?: number | null;
          instance_limit?: number;
          start_date?: string;
          end_date?: string | null;
          local_start_time?: string;
          local_end_time?: string;
          timezone?: string;
          requester_first_name?: string;
          requester_last_name?: string;
          requester_email?: string;
          requester_phone?: string;
          ministry_id?: string | null;
          other_ministry_name?: string | null;
          purpose?: string;
          estimated_attendance?: number;
          setup_requirements?: string | null;
          requester_notes?: string | null;
          admin_notes?: string | null;
          notify_requester?: boolean;
          materialized_through?: string | null;
          paused_reason?: string | null;
          materialization_claim_id?: string | null;
          materialization_claimed_at?: string | null;
          ended_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "reservation_series_created_by_user_id_fkey";
            columns: ["created_by_user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "reservation_series_ministry_id_fkey";
            columns: ["ministry_id"];
            isOneToOne: false;
            referencedRelation: "ministries";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "reservation_series_room_id_fkey";
            columns: ["room_id"];
            isOneToOne: false;
            referencedRelation: "rooms";
            referencedColumns: ["id"];
          },
        ];
      };
      reservation_series_exceptions: {
        Row: {
          id: string;
          series_id: string;
          occurrence_date: string;
          reason: string;
          message: string;
          resolved_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          series_id: string;
          occurrence_date: string;
          reason: string;
          message: string;
          resolved_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          series_id?: string;
          occurrence_date?: string;
          reason?: string;
          message?: string;
          resolved_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "reservation_series_exceptions_series_id_fkey";
            columns: ["series_id"];
            isOneToOne: false;
            referencedRelation: "reservation_series";
            referencedColumns: ["id"];
          },
        ];
      };
      reservations: {
        Row: {
          id: string;
          reference_code: string;
          status: Database["public"]["Enums"]["reservation_status"];
          source: Database["public"]["Enums"]["reservation_source"];
          room_id: string;
          start_at: string;
          end_at: string;
          reservation_range: string | null;
          requester_first_name: string;
          requester_last_name: string;
          requester_email: string;
          requester_phone: string;
          ministry_id: string | null;
          other_ministry_name: string | null;
          purpose: string;
          estimated_attendance: number;
          setup_requirements: string | null;
          requester_notes: string | null;
          admin_notes: string | null;
          requester_message: string | null;
          approval_required_at_submission: boolean;
          food_drinks_allowed_at_submission: boolean;
          room_capacity_at_submission: number;
          created_by_user_id: string | null;
          approved_by: string | null;
          approved_at: string | null;
          declined_by: string | null;
          declined_at: string | null;
          cancelled_by_user_id: string | null;
          cancelled_at: string | null;
          cancelled_by_requester: boolean;
          guest_token_hash: string;
          guest_token_seed: string;
          search_text: string | null;
          created_at: string;
          updated_at: string;
          series_id: string | null;
          occurrence_date: string | null;
          privacy_accepted_at: string | null;
          privacy_version: string | null;
          terms_accepted_at: string | null;
          terms_version: string | null;
        };
        Insert: {
          id?: string;
          reference_code: string;
          status: Database["public"]["Enums"]["reservation_status"];
          source?: Database["public"]["Enums"]["reservation_source"];
          room_id: string;
          start_at: string;
          end_at: string;
          reservation_range?: never;
          requester_first_name: string;
          requester_last_name: string;
          requester_email: string;
          requester_phone: string;
          ministry_id?: string | null;
          other_ministry_name?: string | null;
          purpose: string;
          estimated_attendance: number;
          setup_requirements?: string | null;
          requester_notes?: string | null;
          admin_notes?: string | null;
          requester_message?: string | null;
          approval_required_at_submission: boolean;
          food_drinks_allowed_at_submission: boolean;
          room_capacity_at_submission: number;
          created_by_user_id?: string | null;
          approved_by?: string | null;
          approved_at?: string | null;
          declined_by?: string | null;
          declined_at?: string | null;
          cancelled_by_user_id?: string | null;
          cancelled_at?: string | null;
          cancelled_by_requester?: boolean;
          guest_token_hash: string;
          guest_token_seed: string;
          search_text?: never;
          created_at?: string;
          updated_at?: string;
          series_id?: string | null;
          occurrence_date?: string | null;
          privacy_accepted_at?: string | null;
          privacy_version?: string | null;
          terms_accepted_at?: string | null;
          terms_version?: string | null;
        };
        Update: {
          id?: string;
          reference_code?: string;
          status?: Database["public"]["Enums"]["reservation_status"];
          source?: Database["public"]["Enums"]["reservation_source"];
          room_id?: string;
          start_at?: string;
          end_at?: string;
          reservation_range?: never;
          requester_first_name?: string;
          requester_last_name?: string;
          requester_email?: string;
          requester_phone?: string;
          ministry_id?: string | null;
          other_ministry_name?: string | null;
          purpose?: string;
          estimated_attendance?: number;
          setup_requirements?: string | null;
          requester_notes?: string | null;
          admin_notes?: string | null;
          requester_message?: string | null;
          approval_required_at_submission?: boolean;
          food_drinks_allowed_at_submission?: boolean;
          room_capacity_at_submission?: number;
          created_by_user_id?: string | null;
          approved_by?: string | null;
          approved_at?: string | null;
          declined_by?: string | null;
          declined_at?: string | null;
          cancelled_by_user_id?: string | null;
          cancelled_at?: string | null;
          cancelled_by_requester?: boolean;
          guest_token_hash?: string;
          guest_token_seed?: string;
          search_text?: never;
          created_at?: string;
          updated_at?: string;
          series_id?: string | null;
          occurrence_date?: string | null;
          privacy_accepted_at?: string | null;
          privacy_version?: string | null;
          terms_accepted_at?: string | null;
          terms_version?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "reservations_approved_by_fkey";
            columns: ["approved_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "reservations_cancelled_by_user_id_fkey";
            columns: ["cancelled_by_user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "reservations_created_by_user_id_fkey";
            columns: ["created_by_user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "reservations_declined_by_fkey";
            columns: ["declined_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "reservations_ministry_id_fkey";
            columns: ["ministry_id"];
            isOneToOne: false;
            referencedRelation: "ministries";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "reservations_room_id_fkey";
            columns: ["room_id"];
            isOneToOne: false;
            referencedRelation: "rooms";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "reservations_series_id_fkey";
            columns: ["series_id"];
            isOneToOne: false;
            referencedRelation: "reservation_series";
            referencedColumns: ["id"];
          },
        ];
      };
      room_amenities: {
        Row: {
          room_id: string;
          amenity_id: string;
        };
        Insert: {
          room_id: string;
          amenity_id: string;
        };
        Update: {
          room_id?: string;
          amenity_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "room_amenities_amenity_id_fkey";
            columns: ["amenity_id"];
            isOneToOne: false;
            referencedRelation: "amenities";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "room_amenities_room_id_fkey";
            columns: ["room_id"];
            isOneToOne: false;
            referencedRelation: "rooms";
            referencedColumns: ["id"];
          },
        ];
      };
      rooms: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          location: string | null;
          capacity: number;
          image_path: string | null;
          active: boolean;
          reservable: boolean;
          unavailable_message: string | null;
          approval_required: boolean;
          max_advance_value: number | null;
          max_advance_unit: Database["public"]["Enums"]["advance_unit"] | null;
          food_drinks_allowed: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          location?: string | null;
          capacity: number;
          image_path?: string | null;
          active?: boolean;
          reservable?: boolean;
          unavailable_message?: string | null;
          approval_required?: boolean;
          max_advance_value?: number | null;
          max_advance_unit?: Database["public"]["Enums"]["advance_unit"] | null;
          food_drinks_allowed?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          location?: string | null;
          capacity?: number;
          image_path?: string | null;
          active?: boolean;
          reservable?: boolean;
          unavailable_message?: string | null;
          approval_required?: boolean;
          max_advance_value?: number | null;
          max_advance_unit?: Database["public"]["Enums"]["advance_unit"] | null;
          food_drinks_allowed?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
        ];
      };
      system_email_logs: {
        Row: {
          id: string;
          recipient: string;
          event_type: string;
          entity_type: string;
          entity_id: string;
          payload: Json;
          status: Database["public"]["Enums"]["email_status"];
          provider_message_id: string | null;
          error_message: string | null;
          attempt_count: number;
          last_attempt_at: string | null;
          sent_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          recipient: string;
          event_type: string;
          entity_type: string;
          entity_id: string;
          payload?: Json;
          status?: Database["public"]["Enums"]["email_status"];
          provider_message_id?: string | null;
          error_message?: string | null;
          attempt_count?: number;
          last_attempt_at?: string | null;
          sent_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          recipient?: string;
          event_type?: string;
          entity_type?: string;
          entity_id?: string;
          payload?: Json;
          status?: Database["public"]["Enums"]["email_status"];
          provider_message_id?: string | null;
          error_message?: string | null;
          attempt_count?: number;
          last_attempt_at?: string | null;
          sent_at?: string | null;
          created_at?: string;
        };
        Relationships: [
        ];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      admin_audit_log: {
        Args: { p_search?: string; p_entity_type?: string; p_limit?: number; p_offset?: number };
        Returns: { id: number; created_at: string; actor_kind: Database["public"]["Enums"]["actor_kind"]; actor_name: string; action: string; entity_type: string; entity_id: string; metadata: Json; total_count: number }[];
      };
      admin_calendar: {
        Args: { p_from: string; p_to: string; p_room_id?: string; p_include_cancelled?: boolean };
        Returns: { id: string; reference_code: string; status: Database["public"]["Enums"]["reservation_status"]; room_id: string; room_name: string; start_at: string; end_at: string; requester_first_name: string; requester_last_name: string; ministry_name: string; purpose: string }[];
      };
      admin_dashboard: {
        Args: never;
        Returns: { pending_count: number; approved_today_count: number; upcoming_count: number; week_count: number }[];
      };
      admin_end_reservation_series: {
        Args: { p_id: string };
        Returns: boolean;
      };
      admin_export_reservations: {
        Args: { p_from: string; p_to: string; p_search?: string; p_statuses?: Database["public"]["Enums"]["reservation_status"][]; p_room_id?: string; p_ministry_id?: string; p_approval?: string; p_sort?: string; p_limit?: number };
        Returns: { id: string; reference_code: string; status: Database["public"]["Enums"]["reservation_status"]; source: Database["public"]["Enums"]["reservation_source"]; room_name: string; start_at: string; end_at: string; requester_first_name: string; requester_last_name: string; requester_email: string; requester_phone: string; ministry_name: string; purpose: string; estimated_attendance: number; approval_required_at_submission: boolean; created_at: string }[];
      };
      admin_get_reservation: {
        Args: { p_id: string };
        Returns: { id: string; reference_code: string; status: Database["public"]["Enums"]["reservation_status"]; source: Database["public"]["Enums"]["reservation_source"]; room_id: string; room_name: string; room_slug: string; room_capacity: number; room_food_drinks_allowed: boolean; room_approval_required: boolean; start_at: string; end_at: string; requester_first_name: string; requester_last_name: string; requester_email: string; requester_phone: string; ministry_id: string; ministry_name: string; other_ministry_name: string; purpose: string; estimated_attendance: number; setup_requirements: string; requester_notes: string; admin_notes: string; requester_message: string; approval_required_at_submission: boolean; food_drinks_allowed_at_submission: boolean; room_capacity_at_submission: number; created_by_name: string; approved_by_name: string; approved_at: string; declined_by_name: string; declined_at: string; cancelled_by_name: string; cancelled_at: string; cancelled_by_requester: boolean; created_at: string; updated_at: string }[];
      };
      admin_get_reservation_series: {
        Args: { p_id: string };
        Returns: Json;
      };
      admin_list_amenities: {
        Args: never;
        Returns: { id: string; name: string; icon: string; active: boolean; sort_order: number }[];
      };
      admin_list_ministries: {
        Args: never;
        Returns: { id: string; name: string; active: boolean; sort_order: number; reservation_count: number }[];
      };
      admin_list_reservations: {
        Args: { p_search?: string; p_statuses?: Database["public"]["Enums"]["reservation_status"][]; p_room_id?: string; p_ministry_id?: string; p_from?: string; p_to?: string; p_approval?: string; p_sort?: string; p_limit?: number; p_offset?: number };
        Returns: { id: string; reference_code: string; status: Database["public"]["Enums"]["reservation_status"]; source: Database["public"]["Enums"]["reservation_source"]; room_id: string; room_name: string; room_capacity: number; start_at: string; end_at: string; requester_first_name: string; requester_last_name: string; requester_email: string; requester_phone: string; ministry_name: string; purpose: string; estimated_attendance: number; approval_required_at_submission: boolean; approved_by: string; created_at: string; total_count: number }[];
      };
      admin_list_rooms: {
        Args: never;
        Returns: { id: string; name: string; slug: string; description: string; location: string; capacity: number; image_path: string; active: boolean; reservable: boolean; unavailable_message: string; approval_required: boolean; max_advance_value: number; max_advance_unit: Database["public"]["Enums"]["advance_unit"]; food_drinks_allowed: boolean; sort_order: number; amenity_ids: string[]; upcoming_count: number; updated_at: string }[];
      };
      admin_list_users: {
        Args: never;
        Returns: { id: string; email: string; full_name: string; role: Database["public"]["Enums"]["app_role"]; active: boolean; created_at: string; last_sign_in_at: string }[];
      };
      admin_reservation_emails: {
        Args: { p_id: string };
        Returns: { id: string; recipient: string; event_type: string; status: Database["public"]["Enums"]["email_status"]; error_message: string; attempt_count: number; sent_at: string; created_at: string }[];
      };
      admin_reservation_series_links: {
        Args: { p_ids: string[] };
        Returns: { reservation_id: string; series_id: string; occurrence_date: string }[];
      };
      approve_reservation: {
        Args: { p_id: string; p_message?: string };
        Returns: Database["public"]["Enums"]["reservation_status"];
      };
      booking_horizon_date: {
        Args: { p_room_id: string; p_at?: string };
        Returns: string;
      };
      bootstrap_first_super_admin: {
        Args: { p_user_id: string; p_full_name: string };
        Returns: undefined;
      };
      cancel_guest_reservation: {
        Args: { p_reference: string; p_token_hash: string };
        Returns: Database["public"]["Enums"]["reservation_status"];
      };
      cancel_reservation: {
        Args: { p_id: string; p_message?: string };
        Returns: Database["public"]["Enums"]["reservation_status"];
      };
      claim_emails: {
        Args: { p_limit?: number; p_reservation_id?: string };
        Returns: string[];
      };
      claim_series_to_materialize: {
        Args: { p_limit?: number };
        Returns: { id: string; claim_id: string; room_id: string; frequency: string; interval_count: number; weekdays: number[]; weekday: number; month_ordinals: number[]; month_ordinal: number; day_of_month: number; month_of_year: number; instance_limit: number; start_date: string; end_date: string; local_start_time: string; local_end_time: string; timezone: string; materialized_through: string; target_through: string; occurrence_count: number }[];
      };
      claim_system_emails: {
        Args: { p_limit?: number; p_entity_id?: string };
        Returns: string[];
      };
      complete_email: {
        Args: { p_id: string; p_status: Database["public"]["Enums"]["email_status"]; p_provider_message_id?: string; p_error?: string };
        Returns: undefined;
      };
      complete_staff_password_setup: {
        Args: never;
        Returns: boolean;
      };
      complete_system_email: {
        Args: { p_id: string; p_status: Database["public"]["Enums"]["email_status"]; p_provider_message_id?: string; p_error?: string };
        Returns: undefined;
      };
      create_guest_reservation: {
        Args: { p_room_id: string; p_start_at: string; p_end_at: string; p_first_name: string; p_last_name: string; p_email: string; p_phone: string; p_purpose: string; p_estimated_attendance: number; p_token_hash: string; p_token_seed: string; p_privacy_accepted: boolean; p_terms_accepted: boolean; p_privacy_version: string; p_terms_version: string; p_ministry_id?: string; p_other_ministry_name?: string; p_setup_requirements?: string; p_requester_notes?: string };
        Returns: { id: string; reference_code: string; status: Database["public"]["Enums"]["reservation_status"] }[];
      };
      create_recurring_reservation_series: {
        Args: { p_room_id: string; p_frequency: string; p_interval_count: number; p_weekdays: number[]; p_weekday: number; p_month_ordinals: number[]; p_month_ordinal: number; p_day_of_month: number; p_month_of_year: number; p_instance_limit: number; p_start_date: string; p_end_date: string; p_local_start_time: string; p_local_end_time: string; p_timezone: string; p_first_name: string; p_last_name: string; p_email: string; p_phone: string; p_purpose: string; p_estimated_attendance: number; p_occurrences: Json; p_materialized_through: string; p_ministry_id?: string; p_other_ministry_name?: string; p_setup_requirements?: string; p_requester_notes?: string; p_admin_notes?: string; p_notify?: boolean };
        Returns: { series_id: string; occurrence_count: number }[];
      };
      create_staff_profile: {
        Args: { p_user_id: string; p_full_name: string; p_role: Database["public"]["Enums"]["app_role"] };
        Returns: undefined;
      };
      create_staff_reservation: {
        Args: { p_room_id: string; p_start_at: string; p_end_at: string; p_first_name: string; p_last_name: string; p_email: string; p_phone: string; p_purpose: string; p_estimated_attendance: number; p_token_hash: string; p_token_seed: string; p_ministry_id?: string; p_other_ministry_name?: string; p_setup_requirements?: string; p_requester_notes?: string; p_admin_notes?: string; p_notify?: boolean };
        Returns: { id: string; reference_code: string }[];
      };
      current_staff_profile: {
        Args: never;
        Returns: { id: string; email: string; full_name: string; role: Database["public"]["Enums"]["app_role"]; active: boolean; email_notifications: boolean }[];
      };
      decline_reservation: {
        Args: { p_id: string; p_message?: string; p_admin_note?: string };
        Returns: Database["public"]["Enums"]["reservation_status"];
      };
      email_context: {
        Args: { p_email_id: string };
        Returns: { email_id: string; recipient: string; event_type: string; attempt_count: number; reservation_id: string; reference_code: string; status: Database["public"]["Enums"]["reservation_status"]; room_name: string; room_capacity: number; start_at: string; end_at: string; requester_first_name: string; requester_last_name: string; requester_email: string; requester_phone: string; ministry_name: string; purpose: string; estimated_attendance: number; setup_requirements: string; requester_notes: string; requester_message: string; food_drinks_allowed: boolean; approval_required: boolean; cancelled_by_requester: boolean; guest_token_seed: string; church_name: string; app_name: string; timezone: string; contact_email: string; contact_phone: string; email_sender_name: string }[];
      };
      get_admin_settings: {
        Args: never;
        Returns: Database["public"]["Tables"]["app_settings"]["Row"];
      };
      get_guest_reservation: {
        Args: { p_reference: string; p_token_hash: string };
        Returns: { id: string; reference_code: string; status: Database["public"]["Enums"]["reservation_status"]; room_name: string; room_slug: string; room_capacity: number; start_at: string; end_at: string; requester_first_name: string; ministry_name: string; purpose: string; estimated_attendance: number; setup_requirements: string; requester_notes: string; requester_message: string; approval_required_at_submission: boolean; food_drinks_allowed_at_submission: boolean; room_capacity_at_submission: number; created_at: string; approved_at: string; declined_at: string; cancelled_at: string; cancelled_by_requester: boolean; can_cancel: boolean }[];
      };
      get_public_busy_blocks: {
        Args: { p_from: string; p_to: string; p_room_ids?: string[] };
        Returns: { room_id: string; start_at: string; end_at: string }[];
      };
      hit_rate_limit: {
        Args: { p_bucket: string; p_key_hash: string; p_limit: number; p_window_seconds: number };
        Returns: boolean;
      };
      mark_notifications_read: {
        Args: { p_ids?: string[] };
        Returns: number;
      };
      materialize_series_occurrences: {
        Args: { p_series_id: string; p_claim_id: string; p_occurrences: Json; p_materialized_through: string; p_exceptions?: Json };
        Returns: { created_count: number; exception_count: number; series_status: string }[];
      };
      my_notifications: {
        Args: { p_unread_only?: boolean; p_limit?: number; p_offset?: number };
        Returns: { id: string; type: string; title: string; message: string; reservation_id: string; read_at: string; created_at: string; total_count: number }[];
      };
      record_staff_login: {
        Args: { p_method?: string };
        Returns: undefined;
      };
      retry_email: {
        Args: { p_id: string };
        Returns: undefined;
      };
      save_amenity: {
        Args: { p_name: string; p_icon: string; p_active?: boolean; p_id?: string };
        Returns: string;
      };
      save_ministry: {
        Args: { p_name: string; p_active: boolean; p_sort_order: number; p_id?: string };
        Returns: string;
      };
      save_room: {
        Args: { p_name: string; p_slug: string; p_capacity: number; p_approval_required: boolean; p_food_drinks_allowed: boolean; p_active: boolean; p_reservable: boolean; p_sort_order: number; p_amenity_ids: string[]; p_description?: string; p_location?: string; p_unavailable_message?: string; p_max_advance_value?: number; p_max_advance_unit?: Database["public"]["Enums"]["advance_unit"]; p_id?: string };
        Returns: string;
      };
      set_room_image: {
        Args: { p_id: string; p_image_path?: string };
        Returns: undefined;
      };
      set_user_active: {
        Args: { p_user_id: string; p_active: boolean };
        Returns: undefined;
      };
      set_user_role: {
        Args: { p_user_id: string; p_role: Database["public"]["Enums"]["app_role"] };
        Returns: undefined;
      };
      system_email_context: {
        Args: { p_email_id: string };
        Returns: Json;
      };
      unread_notification_count: {
        Args: never;
        Returns: number;
      };
      update_admin_notes: {
        Args: { p_id: string; p_admin_notes: string };
        Returns: undefined;
      };
      update_app_settings: {
        Args: { p_church_name: string; p_app_name: string; p_timezone: string; p_booking_interval_minutes: number; p_default_max_advance_value: number; p_default_max_advance_unit: Database["public"]["Enums"]["advance_unit"]; p_min_lead_time_minutes: number; p_bookable_day_start: string; p_bookable_day_end: string; p_allow_guest_cancellation: boolean; p_extra_admin_notification_emails: string[]; p_email_sender_name: string; p_contact_email?: string; p_contact_phone?: string };
        Returns: undefined;
      };
      update_reservation: {
        Args: { p_id: string; p_room_id: string; p_start_at: string; p_end_at: string; p_first_name: string; p_last_name: string; p_email: string; p_phone: string; p_purpose: string; p_estimated_attendance: number; p_ministry_id?: string; p_other_ministry_name?: string; p_setup_requirements?: string; p_requester_notes?: string; p_admin_notes?: string; p_notify?: boolean };
        Returns: boolean;
      };
    };
    Enums: {
      actor_kind: "guest" | "staff" | "system";
      advance_unit: "day" | "week" | "month";
      app_role: "admin" | "super_admin";
      email_status: "queued" | "sending" | "sent" | "failed" | "skipped";
      reservation_source: "guest" | "admin";
      reservation_status: "pending" | "approved" | "declined" | "cancelled";
    };
    CompositeTypes: { [_ in never]: never };
  };
};

type PublicSchema = Database["public"];
export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"];
export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"];
export type Enums<T extends keyof PublicSchema["Enums"]> = PublicSchema["Enums"][T];

export const Constants = {
  public: {
    Enums: {
      actor_kind: ["guest", "staff", "system"],
      advance_unit: ["day", "week", "month"],
      app_role: ["admin", "super_admin"],
      email_status: ["queued", "sending", "sent", "failed", "skipped"],
      reservation_source: ["guest", "admin"],
      reservation_status: ["pending", "approved", "declined", "cancelled"],
    },
  },
} as const;
