// GENERATED by scripts/generate-db-types.ts from supabase/migrations — do not edit.
// Regenerate with `npm run db:types` after changing a migration.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  __InternalSupabase: { PostgrestVersion: "13" };
  public: {
    Tables: {
      amenities: {
        Row: {
          id: string;
          name: string;
          icon: string | null;
          active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          icon?: string | null;
          active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          icon?: string | null;
          active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
        ];
      };
      app_settings: {
        Row: {
          id: boolean;
          church_name: string;
          app_name: string;
          timezone: string;
          contact_email: string | null;
          contact_phone: string | null;
          booking_interval_minutes: number;
          default_max_advance_value: number;
          default_max_advance_unit: Database["public"]["Enums"]["advance_unit"];
          min_lead_time_minutes: number;
          bookable_day_start: string;
          bookable_day_end: string;
          allow_guest_cancellation: boolean;
          extra_admin_notification_emails: string[];
          email_sender_name: string;
          updated_at: string;
          updated_by: string | null;
        };
        Insert: {
          id?: boolean;
          church_name?: string;
          app_name?: string;
          timezone?: string;
          contact_email?: string | null;
          contact_phone?: string | null;
          booking_interval_minutes?: number;
          default_max_advance_value?: number;
          default_max_advance_unit?: Database["public"]["Enums"]["advance_unit"];
          min_lead_time_minutes?: number;
          bookable_day_start?: string;
          bookable_day_end?: string;
          allow_guest_cancellation?: boolean;
          extra_admin_notification_emails?: string[];
          email_sender_name?: string;
          updated_at?: string;
          updated_by?: string | null;
        };
        Update: {
          id?: boolean;
          church_name?: string;
          app_name?: string;
          timezone?: string;
          contact_email?: string | null;
          contact_phone?: string | null;
          booking_interval_minutes?: number;
          default_max_advance_value?: number;
          default_max_advance_unit?: Database["public"]["Enums"]["advance_unit"];
          min_lead_time_minutes?: number;
          bookable_day_start?: string;
          bookable_day_end?: string;
          allow_guest_cancellation?: boolean;
          extra_admin_notification_emails?: string[];
          email_sender_name?: string;
          updated_at?: string;
          updated_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "app_settings_updated_by_fkey";
            columns: ["updated_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      audit_logs: {
        Row: {
          id: number;
          actor_user_id: string | null;
          actor_kind: Database["public"]["Enums"]["actor_kind"];
          action: string;
          entity_type: string;
          entity_id: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: never;
          actor_user_id?: string | null;
          actor_kind: Database["public"]["Enums"]["actor_kind"];
          action: string;
          entity_type: string;
          entity_id?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: never;
          actor_user_id?: string | null;
          actor_kind?: Database["public"]["Enums"]["actor_kind"];
          action?: string;
          entity_type?: string;
          entity_id?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "audit_logs_actor_user_id_fkey";
            columns: ["actor_user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      email_logs: {
        Row: {
          id: string;
          reservation_id: string | null;
          recipient: string;
          event_type: string;
          status: Database["public"]["Enums"]["email_status"];
          provider_message_id: string | null;
          error_message: string | null;
          attempt_count: number;
          last_attempt_at: string | null;
          sent_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          reservation_id?: string | null;
          recipient: string;
          event_type: string;
          status?: Database["public"]["Enums"]["email_status"];
          provider_message_id?: string | null;
          error_message?: string | null;
          attempt_count?: number;
          last_attempt_at?: string | null;
          sent_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          reservation_id?: string | null;
          recipient?: string;
          event_type?: string;
          status?: Database["public"]["Enums"]["email_status"];
          provider_message_id?: string | null;
          error_message?: string | null;
          attempt_count?: number;
          last_attempt_at?: string | null;
          sent_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "email_logs_reservation_id_fkey";
            columns: ["reservation_id"];
            isOneToOne: false;
            referencedRelation: "reservations";
            referencedColumns: ["id"];
          },
        ];
      };
      ministries: {
        Row: {
          id: string;
          name: string;
          active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
        ];
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: string;
          title: string;
          message: string;
          reservation_id: string | null;
          read_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: string;
          title: string;
          message: string;
          reservation_id?: string | null;
          read_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: string;
          title?: string;
          message?: string;
          reservation_id?: string | null;
          read_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "notifications_reservation_id_fkey";
            columns: ["reservation_id"];
            isOneToOne: false;
            referencedRelation: "reservations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "notifications_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string;
          role: Database["public"]["Enums"]["app_role"];
          active: boolean;
          email_notifications: boolean;
          invited_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name: string;
          role?: Database["public"]["Enums"]["app_role"];
          active?: boolean;
          email_notifications?: boolean;
          invited_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string;
          role?: Database["public"]["Enums"]["app_role"];
          active?: boolean;
          email_notifications?: boolean;
          invited_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "profiles_invited_by_fkey";
            columns: ["invited_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      rate_limit_events: {
        Row: {
          id: number;
          bucket: string;
          key_hash: string;
          created_at: string;
        };
        Insert: {
          id?: never;
          bucket: string;
          key_hash: string;
          created_at?: string;
        };
        Update: {
          id?: never;
          bucket?: string;
          key_hash?: string;
          created_at?: string;
        };
        Relationships: [
        ];
      };
      reservations: {
        Row: {
          id: string;
          reference_code: string;
          status: Database["public"]["Enums"]["reservation_status"];
          source: Database["public"]["Enums"]["reservation_source"];
          room_id: string;
          start_at: string;
          end_at: string;
          reservation_range: string | null;
          requester_first_name: string;
          requester_last_name: string;
          requester_email: string;
          requester_phone: string;
          ministry_id: string | null;
          other_ministry_name: string | null;
          purpose: string;
          estimated_attendance: number;
          setup_requirements: string | null;
          requester_notes: string | null;
          admin_notes: string | null;
          requester_message: string | null;
          approval_required_at_submission: boolean;
          food_drinks_allowed_at_submission: boolean;
          room_capacity_at_submission: number;
          created_by_user_id: string | null;
          approved_by: string | null;
          approved_at: string | null;
          declined_by: string | null;
          declined_at: string | null;
          cancelled_by_user_id: string | null;
          cancelled_at: string | null;
          cancelled_by_requester: boolean;
          guest_token_hash: string;
          search_text: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          reference_code: string;
          status: Database["public"]["Enums"]["reservation_status"];
          source?: Database["public"]["Enums"]["reservation_source"];
          room_id: string;
          start_at: string;
          end_at: string;
          reservation_range?: never;
          requester_first_name: string;
          requester_last_name: string;
          requester_email: string;
          requester_phone: string;
          ministry_id?: string | null;
          other_ministry_name?: string | null;
          purpose: string;
          estimated_attendance: number;
          setup_requirements?: string | null;
          requester_notes?: string | null;
          admin_notes?: string | null;
          requester_message?: string | null;
          approval_required_at_submission: boolean;
          food_drinks_allowed_at_submission: boolean;
          room_capacity_at_submission: number;
          created_by_user_id?: string | null;
          approved_by?: string | null;
          approved_at?: string | null;
          declined_by?: string | null;
          declined_at?: string | null;
          cancelled_by_user_id?: string | null;
          cancelled_at?: string | null;
          cancelled_by_requester?: boolean;
          guest_token_hash: string;
          search_text?: never;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          reference_code?: string;
          status?: Database["public"]["Enums"]["reservation_status"];
          source?: Database["public"]["Enums"]["reservation_source"];
          room_id?: string;
          start_at?: string;
          end_at?: string;
          reservation_range?: never;
          requester_first_name?: string;
          requester_last_name?: string;
          requester_email?: string;
          requester_phone?: string;
          ministry_id?: string | null;
          other_ministry_name?: string | null;
          purpose?: string;
          estimated_attendance?: number;
          setup_requirements?: string | null;
          requester_notes?: string | null;
          admin_notes?: string | null;
          requester_message?: string | null;
          approval_required_at_submission?: boolean;
          food_drinks_allowed_at_submission?: boolean;
          room_capacity_at_submission?: number;
          created_by_user_id?: string | null;
          approved_by?: string | null;
          approved_at?: string | null;
          declined_by?: string | null;
          declined_at?: string | null;
          cancelled_by_user_id?: string | null;
          cancelled_at?: string | null;
          cancelled_by_requester?: boolean;
          guest_token_hash?: string;
          search_text?: never;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "reservations_approved_by_fkey";
            columns: ["approved_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "reservations_cancelled_by_user_id_fkey";
            columns: ["cancelled_by_user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "reservations_created_by_user_id_fkey";
            columns: ["created_by_user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "reservations_declined_by_fkey";
            columns: ["declined_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "reservations_ministry_id_fkey";
            columns: ["ministry_id"];
            isOneToOne: false;
            referencedRelation: "ministries";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "reservations_room_id_fkey";
            columns: ["room_id"];
            isOneToOne: false;
            referencedRelation: "rooms";
            referencedColumns: ["id"];
          },
        ];
      };
      room_amenities: {
        Row: {
          room_id: string;
          amenity_id: string;
        };
        Insert: {
          room_id: string;
          amenity_id: string;
        };
        Update: {
          room_id?: string;
          amenity_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "room_amenities_amenity_id_fkey";
            columns: ["amenity_id"];
            isOneToOne: false;
            referencedRelation: "amenities";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "room_amenities_room_id_fkey";
            columns: ["room_id"];
            isOneToOne: false;
            referencedRelation: "rooms";
            referencedColumns: ["id"];
          },
        ];
      };
      rooms: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          location: string | null;
          capacity: number;
          image_path: string | null;
          active: boolean;
          reservable: boolean;
          unavailable_message: string | null;
          approval_required: boolean;
          max_advance_value: number | null;
          max_advance_unit: Database["public"]["Enums"]["advance_unit"] | null;
          food_drinks_allowed: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          location?: string | null;
          capacity: number;
          image_path?: string | null;
          active?: boolean;
          reservable?: boolean;
          unavailable_message?: string | null;
          approval_required?: boolean;
          max_advance_value?: number | null;
          max_advance_unit?: Database["public"]["Enums"]["advance_unit"] | null;
          food_drinks_allowed?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          location?: string | null;
          capacity?: number;
          image_path?: string | null;
          active?: boolean;
          reservable?: boolean;
          unavailable_message?: string | null;
          approval_required?: boolean;
          max_advance_value?: number | null;
          max_advance_unit?: Database["public"]["Enums"]["advance_unit"] | null;
          food_drinks_allowed?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
        ];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      booking_horizon_date: {
        Args: { p_room_id: string; p_at?: string };
        Returns: string;
      };
      bootstrap_first_super_admin: {
        Args: { p_user_id: string; p_full_name: string };
        Returns: undefined;
      };
      get_admin_settings: {
        Args: never;
        Returns: Database["public"]["Tables"]["app_settings"]["Row"];
      };
      get_public_busy_blocks: {
        Args: { p_from: string; p_to: string; p_room_ids?: string[] };
        Returns: { room_id: string; start_at: string; end_at: string }[];
      };
    };
    Enums: {
      actor_kind: "guest" | "staff" | "system";
      advance_unit: "day" | "week" | "month";
      app_role: "admin" | "super_admin";
      email_status: "queued" | "sending" | "sent" | "failed" | "skipped";
      reservation_source: "guest" | "admin";
      reservation_status: "pending" | "approved" | "declined" | "cancelled";
    };
    CompositeTypes: { [_ in never]: never };
  };
};

type PublicSchema = Database["public"];
export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"];
export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"];
export type Enums<T extends keyof PublicSchema["Enums"]> = PublicSchema["Enums"][T];

export const Constants = {
  public: {
    Enums: {
      actor_kind: ["guest", "staff", "system"],
      advance_unit: ["day", "week", "month"],
      app_role: ["admin", "super_admin"],
      email_status: ["queued", "sending", "sent", "failed", "skipped"],
      reservation_source: ["guest", "admin"],
      reservation_status: ["pending", "approved", "declined", "cancelled"],
    },
  },
} as const;
